version: '3'

services: 
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        # command: gunicorn roumpini.wsgi -b 0.0.0.0:8000
        volumes: 
            - .:/code
        ports: 
            - 8000:8000
        environment: 
            - ENVIRONMENT=development
    
    db:
        image: postgres:11
        environment: 
            - POSTGRES_USER=rogue
            - POSTGRES_PASSWORD=rogue
            - POSTGRES_DB=rogue
